services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: event-management-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - event-network

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: event-management-backend
    depends_on:
      - database
    # No environment variables here - we're using application.yml
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - event-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: event-management-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - event-network

networks:
  event-network:
    driver: bridge

volumes:
  postgres_data: